version: '3'

services:
  worker:
    image: rabbitmq-demo-worker
    build: ./worker
    command: wait-for-it.sh --timeout=30 broker:5672 -- php worker.php
    links:
      - broker
    volumes:
      - "./worker/src/code:/code"
    working_dir: /code
  broker:
    image: rabbitmq:3-management
    ports:
      - 80:15672
