version: '3'

services:
  worker:
    image: rabbitmq-demo-worker
    build: ./worker
    command: wait-for-it.sh --timeout=30 broker:5672 -- echo 'run worker now..'
    links:
      - broker
    volumes:
      - "./console/src/www:/var/www/html"
  broker:
    image: rabbitmq:3-management
    ports:
      - 80:15672
